### ISSUE TITLE
Dockerfile?

### ISSUE THREAD

**Issue by danshapir** [camunda-community-hub/zeeqs#129]
I really need a Dockerfile to be able to add the Postgres jar file and in general build a new image. But for some reason there is no such thing in the repo.

Can you please assist?

**Comment by saig0** [comment]
The docker image is built with [Jib](https://github.com/GoogleContainerTools/jib).
The Maven plugin is defined in the [pom.xml](https://github.com/camunda-community-hub/zeeqs/blob/master/app/pom.xml#L49-L67).

I guess that you could use Jib to extend the ZeeQS image. I did something similar for the Zeebe image to include the Hazelcast exporter.

Or, you write your own Dockerfile and use the ZeeQS image as the source image.

Does this help you?

**Comment by danshapir** [comment]
I'll try and understand how to set it up using jib.

Regarding using the current image as a source image, how? 
I'm trying to create a new docker image with postgres built-in since I know literally everyone want and need it, haha.

**Comment by saig0** [comment]
I don't have much experience in writing a Dockerfile. So, I can help here.

With Jib, it could look similar to this: https://github.com/camunda-community-hub/zeebe-hazelcast-exporter/blob/master/exporter/pom.xml#L67-L145

If a ZeeQS image that includes a Postgres driver is useful and requested then we could build it as a part of this repository.

**Comment by danshapir** [comment]
That would be great! Both here and in simple monitor every company I talk to are straggling with the same thing, they want postgres but didn't manage to do it on k8s since the example is with docker compose.

If you could add such a docker it would be a game changer!!!!

**Comment by aivinog1** [comment]
Hey @saig0! I've played a little with code and I see only one option to add Postgres driver to the image: just declare it as a runtime dependency. Also, we can write some integration tests if we want to make sure that everything works fine.

**Comment by saig0** [comment]
Yes, the easiest way is to add the driver directly as a dependency :+1: 
In this case, it would be nice to have some tests to verify that the applications works with Postgres.
