### ISSUE TITLE
Docker image for 2.0.0 not released to Docker Hub

### ISSUE THREAD

**Issue by falko** [camunda-community-hub/zeeqs#153]
https://hub.docker.com/r/camunda/zeeqs/tags?page=1&ordering=last_updated

Could you please provide it so that we can update the Helm charts?

**Comment by saig0** [comment]
The docker image moved to GitHub packages: https://github.com/camunda-community-hub/zeeqs/pkgs/container/zeeqs

I don't plan to push images to DockerHub anymore. Please use `ghcr.io/camunda-community-hub/zeeqs:2.0.0` instead.

@falko is this okay for you?

**Comment by falko** [comment]
Depends on whether this will work: https://github.com/camunda-community-hub/zeebe-zeeqs-helm/pull/7/commits/22130e6abc9e7546a3af1efb648bd2a2407208f9

**Comment by saig0** [comment]
Okay. Please reopen the issue if you see any problem :wink:

**Comment by falko** [comment]
@saig0 it might be good to mention the location of the docker image in the release notes.
