### ISSUE TITLE
Elasticsearch exporter

### ISSUE THREAD

**Issue by fromz** [camunda-community-hub/zeeqs#271]
Hey there, I noticed in https://github.com/camunda-community-hub/zeeqs/blob/master/docs/ZeeQS.png there's reference to being able to use an elasticsearch exporter as input to ZeeQS. Is this currently supported at all? How much of an undertaking, in your estimation, would it be support ES?

**Comment by saig0** [comment]
Please have a look at #5.

Closing this issue in favor of #5.
