### ISSUE TITLE
Does Zeeqs really guarantee the order of events as they occurred?

### ISSUE THREAD

**Issue by younes-io** [camunda-community-hub/zeeqs#277]
I have a Zeebe broker that streams data to a PostgreSQL DB through Zeeqs/Hazelcast.

It seems that events are not always recorded as they actually happened; in other words, the order of events does not seem to be always guaranteed. Here is a screenshot of my PostgreSQL:

![image](https://forum.camunda.io/uploads/default/original/3X/3/5/3564cc892c1fb9ace83b5f860897a22e3bbba0e9.png)

The chat-message event has happened after all other events/variables. Also, between every two chat-message there must always be a userInputText and a watsonResponse; yet, this is not the case as you can see in the chunk shown in the screen. This is not the only case I spotted; there are others…

Could you please let me know if Zeeqs guarantees the order of events as they actually occurred in reality?

Thank you,

**Comment by saig0** [comment]
It depends. The order of the records (i.e. events) should be the same as on the Zeebe log stream. But only for one partition. Records on different partitions are exported independently from each other.

Are the records written to one partition?
Are the records only variables?

Please share an example to reproduce the behavior.

**Comment by younes-io** [comment]
**Are the records written to one partition?**
On my Helm values file, I've got these set up:
```
    partitionCount: "4"
    replicationFactor: "2"
```

On the database, I don't think there is a way to find out which variable is written on which partition. Even if I have that piece of information, I'm not sure it will be helpful since you said export is done independently.

![pgrsql_issue](https://user-images.githubusercontent.com/3153107/192463647-b5acacee-eb7e-4d0f-8f32-5737f1b7bb64.png)

**Are the records only variables?**
No. There are events as well (e.g. `chat-message`)

**Please share an example to reproduce the behavior.**
You mean an example of the BPMN workflow? (FYI, my BPMN workflow calls many APIs; most of them are internal, so I cannot share everything)

**Comment by younes-io** [comment]
Also, something I noticed is that some variables only exist in their latest state. Basically, my BPMN workflow is a loop. In an execution, for instance, it will loop 6 times. I have an `iteration` variable that tracks the current iteration ID, and the only one I have in the export is the sixth (latest) one. Why? Where are the others? (BTW, this variable is incremented within a RECEIVE TASK that triggers the event `chat-message`)

**Comment by younes-io** [comment]
@saig0 : any feedback on this please?

**Comment by saig0** [comment]
All variable updates should be tracked. The updates are stored in the database table `variable_update`. The latest variable values are stored in the table `variable`.

Does this answer your question?

If not, please share an example BPMN process that demonstrates the issue. Currently, I'm not sure about the concrete issue. :sweat_smile:
