### ISSUE TITLE
I can query user tasks 

### ISSUE THREAD

**Issue by saig0** [camunda-community-hub/zeeqs#284]
In Zeebe, user tasks are a special kind of task. They are similar to other tasks but have a few special properties. And they should be completed by users, in form of a user task application (e.g. Tasklist). 

We should handle user tasks as first-class citizens.  

- I can fetch all user tasks of a process instance
- I can query all user tasks
- A user task has the following properties
  - key
  - state (`created` or `completed`)
  - timestamp
  - startTime
  - endTime
  - connection to the processInstance
  - connection to the elementInstance 
  - assignee (i.e. the value of the [custom job header](https://github.com/camunda/zeebe/blob/main/protocol/src/main/java/io/camunda/zeebe/protocol/Protocol.java#L76))
  - candidate groups (i.e. the value of the [custom job header](https://github.com/camunda/zeebe/blob/main/protocol/src/main/java/io/camunda/zeebe/protocol/Protocol.java#L80))
  - connection to the form, based in the value of the [custom job header](https://github.com/camunda/zeebe/blob/main/protocol/src/main/java/io/camunda/zeebe/protocol/Protocol.java#L72)
  - connection to variables (i.e. all visible variables from this element instance; local variables and from upper scopes; required to render the form)
- the forms of the user tasks are embedded in the process
  - import the forms during the import of a process

**Comment by SebastianStamm** [comment]
How can I retrieve the variables that are visible from a user task? E.g. I want to retrieve all user tasks with their variables for a given process instance. I would expect the query to look something like this, but the `variables` field does not exist

```
{
  processInstance(key: $key) {    
    userTasks(perPage: 100) {
      totalCount
      nodes {
        key
        variables
      }
    }
  }
}
```

Context: https://github.com/camunda-community-hub/zeebe-play/blob/7d99ec7b4cbf8eb605814980df934e2008af7dfa/src/main/resources/public/js/zeeqs-client.js#L288-L314

**Comment by saig0** [comment]
@SebastianStamm the variable part was implemented with https://github.com/camunda-community-hub/zeeqs/pull/313. 

As a result, you can use the following query to retrieve the variables for the user tasks. 

```
{
  processInstance(key: $key) {    
    userTasks(perPage: 100) {
      totalCount
      nodes {
        key
        elementInstance {
          variables(localOnly: false) {
            name
            value
          }
        }
      }
    }
  }
}
```

Or, for one specific user task:

```
{
  userTask(key: $key) {
    elementInstance {
      variables(localOnly: false) {
        name
        value
      }
    }
  }
}
```
